// CallEventType.ts
export enum CallEventType {
  INITIAL_CALL_STATE,
  CALL_STATE_CHANGED,
  AUDIO_DEVICES_CHANGED,
  AUDIO_ROUTE_CHANGED,
  CALL_HELD,
  CALL_UNHELD,
  CALL_MUTED,
  CALL_UNMUTED,
  CALL_ANSWERED,
  CALL_REJECTED,
  CALL_ENDED,
}
